"""add is_safe_to_go_out column

Revision ID: 564f568e3df6
Revises: d9146e22e7ee
Create Date: 2025-06-14 19:01:05.386115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564f568e3df6'
down_revision: Union[str, None] = 'd9146e22e7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astronomy_info', sa.Column('is_safe_to_go_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronomy_info', 'is_safe_to_go_out')
    # ### end Alembic commands ###
