"""fix is_safe_to_go_out values

Revision ID: 959c6847df5d
Revises: a314a67e30a0
Create Date: 2025-06-15 11:15:15.466559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959c6847df5d'
down_revision: Union[str, None] = 'a314a67e30a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   
    with op.batch_alter_table("astronomy_info") as batch_op:
        batch_op.drop_column("is_safe_to_go_out")
        enum_type = sa.Enum("YES", "NO", name="safetylevel")
        enum_type.create(op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column("is_safe_to_go_out", enum_type, nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
