"""init weather and astronomy tables

Revision ID: b0aa4dd14ff9
Revises: 
Create Date: 2025-06-13 14:35:24.291700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aa4dd14ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW', name='winddirection'), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('astronomy_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('moon_phase', sa.String(), nullable=True),
    sa.Column('moon_illumination', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('astronomy_info')
    op.drop_table('weather')
    # ### end Alembic commands ###
