"""update winddirection enum

Revision ID: d9146e22e7ee
Revises: 7ac305177c9c
Create Date: 2025-06-14 18:15:35.029388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd9146e22e7ee'
down_revision: Union[str, None] = '7ac305177c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    new_type = ENUM(
        'N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE',
        'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW',
        name='winddirection'
    )
    new_type.create(op.get_bind(), checkfirst=True)

    op.alter_column('weather', 'wind_direction',
                    type_=new_type,
                    postgresql_using='wind_direction::text::winddirection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
